# Generated by Django 4.2.4 on 2023-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the customer.",
                        max_length=250,
                        unique=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(help_text="Enter the Mobile No", max_length=13),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        help_text="Enter the WhatsApp mobile No", max_length=13
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Enter the address of the customer."),
                ),
                (
                    "altaddress",
                    models.TextField(
                        help_text="Enter the alternate address of the customer."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the customer was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the customer was last updated.",
                    ),
                ),
            ],
        ),
    ]
