# Generated by Django 4.2.4 on 2023-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hashing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="altaddress",
            field=models.TextField(
                blank=True,
                help_text="Enter the alternate address of the customer.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Enter the WhatsApp mobile No",
                max_length=13,
                null=True,
            ),
        ),
    ]
