# Generated by Django 4.2.4 on 2023-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hashing", "0002_alter_customer_altaddress_alter_customer_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="creditlimit",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(
                help_text="Enter the address of the customer.", verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="altaddress",
            field=models.TextField(
                blank=True,
                help_text="Enter the alternate address of the customer.",
                null=True,
                verbose_name="Alternate Address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the customer was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(
                help_text="Enter the Mobile No",
                max_length=13,
                verbose_name="Mobile No.",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the customer was last updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Enter the WhatsApp mobile No",
                max_length=13,
                null=True,
                verbose_name="Whatsapp No.",
            ),
        ),
    ]
